sudo: required

# Enable C++ support
language: cpp

# Use Linux by default
os: linux

# Use Ubuntu 18.04 for GCC 7.4.0
dist: bionic

# Compiler selection
compiler:
- gcc
- clang

addons:
  apt:
    update: true
    sources:
    - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
      key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
    - clang-9
    - gcc-9
    - g++-9
    - libglm-dev
    - libboost-dev

install:
  # /usr/bin/gcc points to an older compiler on Linux.
  - if [ "$CXX" = "g++" ]; then export CXX="g++-9" CC="gcc-9"; fi
  # /usr/bin/gcc points to an older compiler on Linux.
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-9" CC="clang-9"; fi
  - echo ${CC}
  - echo ${CXX}
  - ${CXX} --version
  - cmake --version
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - |
    CMAKE_URL="https://cmake.org/files/v3.18/cmake-3.18.0-rc3-Linux-x86_64.tar.gz"
    mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
    export CMAKE_DIR=${DEPS_DIR}/cmake/bin
  - ../scripts/install-catch2.sh
  - ../scripts/install-fastnoise-simd.sh
  - ../scripts/install-libtiff.sh

# Build steps
script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  - ${CMAKE_DIR}/cmake -DBUILD_TESTING=ON .. && make
  - ctest
