sudo: required

# Enable C++ support
language: cpp

# Use Linux by default
os: linux

# Use Ubuntu 18.04 for GCC 7.4.0
dist: bionic

# Compiler selection
compiler: gcc

addons:
  apt:
    update: true
    packages:
    - libglm-dev
    - libboost-dev

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - |
    CMAKE_URL="https://cmake.org/files/v3.18/cmake-3.18.0-rc3-Linux-x86_64.tar.gz"
    mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
    export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  - ../scripts/install-catch2.sh
  - ../scripts/install-fastnoise-simd.sh
  - ../scripts/install-libtiff.sh

# Build steps
script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  - cmake -DBUILD_TESTING=ON .. && make
  - ctest
