sudo: required

# Enable C++ support
language: cpp

# Use Linux by default
os: linux

# Use Ubuntu 18.04 for GCC 7.4.0
dist: bionic

# Compiler selection
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty
    update: true
    packages:
    - cmake
    - cmake-data
    - libglm-dev
    dist: string

before_install:
  - ./install-catch2.sh

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
  - ctest
